### PR TITLE
Update __main__.py

### PR DESCRIPTION
**Pull request by mgw6**
Spelling changed from as_grey to as_gray. [See documentation.](https://scikit-image.org/docs/dev/api/skimage.io.html#skimage.io.imread)

### CODE REVIEW

**Comment by igorcmoura** [comment]
Thank you for correcting it!

**Comment by mgw6** [comment]
You're welcome. The code is very well written, great results.

**Comment by mgw6** [comment]
Hi Igor, 
My name is MacGregor and I am doing summer research at Clarkson University in New York, USA. I would like to use your code for my research. I have attempted to write my own Criminisi code and it works but yours gives better results. If this is not okay with you or you would like to discuss this further, please email me at mwinegar@clarkson.edu. 

Thank you, 

MacGregor

**Comment by igorcmoura** [comment]
Hi MacGregor!
Sure, you can use it as you want 🙂

**Pull request merged**
